teste/Models/EmprestimoViewModel.cs
using teste.DATA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace teste.Models
{
    public class EmprestimoViewModel
    {
        public Livro oLivro { get; set; }
        public Cliente oCliente { get; set; }
        public LivroCliente oLivroClienteEmprestimo { get; set; }
        public DateTime DataEmprestimo { get; set; }
        public DateTime DataDevolucao { get; set; }

        public int IdCliente { get; set; }
        public int IdLivro { get; set; }


        public List<Cliente> oListCliente { get; set; }
        public List<Livro> oListLivro { get; set; }
    }
}

teste/Models/ErrorViewModel.cs
using Microsoft.EntityFrameworkCore;

namespace teste.Models
{
    [Keyless]
    public class ErrorViewModel
    {
      
        public string? RequestId { get; set; }


        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    }
}

teste/Controllers/ClienteController.cs
using teste.DATA.Models;
using teste.DATA.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Collections.Generic;

namespace teste.DATA.Controllers
{
    public class ClienteController : Controller
    {
        public ClienteService oClienteService = new ClienteService();
        public IActionResult Index()
        {
            List<Cliente> oListCliente = oClienteService.oRepositoryCliente.SelecionarTodos();
            return View(oListCliente);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Cliente model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            oClienteService.oRepositoryCliente.Incluir(model);
            return RedirectToAction("Index");
        }
        public IActionResult Details(int id)
        {
            Cliente oCliente = oClienteService.oRepositoryCliente.SelecionarPK(id);
            return View(oCliente);
        }
        public IActionResult Edit(int id)
        {
            Cliente oCliente = oClienteService.oRepositoryCliente.SelecionarPK(id);
            return View(oCliente);
        }
        [HttpPost]
        public IActionResult Edit(Cliente model)
        {
            Cliente oCliente = oClienteService.oRepositoryCliente.Alterar(model);
            int id = oCliente.IdCliente;
            return RedirectToAction("Details", new { id });
        }
        public IActionResult Delete(int id)
        {
            oClienteService.oRepositoryCliente.Excluir(id);
            return RedirectToAction("index");
        }
    }
}

teste/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using teste.Models;

namespace teste.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

teste/Controllers/LivroController.cs
using Microsoft.AspNetCore.Mvc;
using teste.DATA.Models;
using teste.DATA.Services;

namespace teste.Controllers
{
   
    public class LivroController : Controller
    {
        public LivroService oLivroService = new LivroService();
        public IActionResult Index()
        {
            List<Livro> oListLivro = oLivroService.oRepositoryLivro.SelecionarTodos();
            return View(oListLivro);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Livro model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            oLivroService.oRepositoryLivro.Incluir(model);
            return RedirectToAction("Index");
        }
        public IActionResult Details(int id)
        {
            Livro oLivro = oLivroService.oRepositoryLivro.SelecionarPK(id);
            return View(oLivro);
        }
        public IActionResult Edit(int id)
        {
            Livro oLivro = oLivroService.oRepositoryLivro.SelecionarPK(id);
            return View(oLivro);
        }
        [HttpPost]
        public IActionResult Edit(Livro model)
        {
            Livro oLivro = oLivroService.oRepositoryLivro.Alterar(model);
            int id = oLivro.IdLivro;
            return RedirectToAction("Details", new { id });
        }
        public IActionResult Delete(int id)
        {
            oLivroService.oRepositoryLivro.Excluir(id);
            return RedirectToAction("index");
        }
    }
}

teste/Views/Cliente/Create.cshtml
@model teste.DATA.Models.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1>Novo Cliente</h1>

<h4>Preencha os campos abaixo para incluir um novo Cliente </h4>
<hr />
<div>
    <a class="btn btn-primary" asp-action="Index">Voltar</a>
</div>
<br />
<div class="row">
    <div class="col-md">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           <div class="card-header">Informações Pessoais</div>
           <div class ="card-body">

              <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
              </div>

           </div>
            <div class="card">
                <div class="card-header"> Endereço</div>
                <div class="card-body">

                    <div class="form-group">
                    <label asp-for="Endereço" class="control-label"></label>
                    <input asp-for="Endereço" class="form-control" />
                    <span asp-validation-for="Endereço" class="text-danger"></span>
                    </div>
                </div>


            </div>
            <br />
              <div class="card">
                <div class="card-header"> Contato</div>
                <div class="card-body">

               <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Endereço" class="text-danger"></span>
              </div>
             </div>
             </div>

            <div class="form-group">
                <input type="submit" value="Incluir" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

teste/Views/Cliente/Details.cshtml
@model teste.DATA.Models.Cliente

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes do Cliente</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <div>
    <a asp-action="Edit" class="btn btn-success" asp-route-id="@Model.IdCliente">Alterar</a> 
    <a class="btn btn-primary" asp-action="Index">Voltar</a>
</div>

       <div class="card"> 
                   <div class="card-header">Informações do cliente</div>
                   <div class ="card-body">
    <dl class="row">
        <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Endereço)
        </dt>
        <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Endereço)
        </dd>
        <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Telefone)
        </dd>
    </dl>
   </div>
</div>

teste/Views/Cliente/Edit.cshtml
@model teste.DATA.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1>Alterar dados do cliente</h1>

<h4>Altere os dados abaixo</h4>
<hr />
<div>

    <a class="btn btn-primary" asp-action="Index">Voltar</a>
</div>
<br/>
<div class="row">
    <div class="col-md">
        <form asp-action="Edit">
                 <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                 <div hidden class="form-group col-md">
                    <label asp-for="IdCliente" class="control-label"></label>
                    <input asp-for="IdCliente" class="form-control" />

                 </div>



                 <div class="card"> 
                   <div class="card-header">Informações Pessoais</div>
                   <div class ="card-body">

                      <div class="form-group">
                        <label asp-for="Nome" class="control-label"></label>
                        <input asp-for="Nome" class="form-control" />
                        <span asp-validation-for="Nome" class="text-danger"></span>
                      </div>
                  </div>
                   </div>
                    <div class="card">
                        <div class="card-header"> Endereço</div>
                        <div class="card-body">

                                <div class="form-group">
                                <label asp-for="Endereço" class="control-label"></label>
                                <input asp-for="Endereço" class="form-control" />
                                <span asp-validation-for="Endereço" class="text-danger"></span>
                                </div>
                            </div>


                        </div>
                        <br />
                          <div class="card">
                            <div class="card-header"> Contato</div>
                            <div class="card-body">

                           <div class="form-group">
                            <label asp-for="Telefone" class="control-label"></label>
                            <input asp-for="Telefone" class="form-control" />
                            <span asp-validation-for="Endereço" class="text-danger"></span>
                          </div>
                         </div>
                         </div>

                        <div class="form-group">
                            <input type="submit" value="Incluir" class="btn btn-success" />
                        </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

teste/Views/Cliente/Index.cshtml
@model IEnumerable<teste.DATA.Models.Cliente>
@{
    ViewData["Title"] = "Index";
}

<h1>Cliente</h1>

<p>
    <a class="btn btn-primary" asp-action="Create"> <i class="fa fa-plus-circle"></i> Novo cliente</a>
</p>
<table id="myTable" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Endereço)
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Telefone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Endereço)
                </td>
                
                <td class="row">

                         <a asp-action="Edit" class="btn btn-primary mr-1"asp-route-id="@item.IdCliente">Alterar</a> 
                        <a asp-action="Details" class="btn btn-success mr-1"asp-route-id="@item.IdCliente">Datalhes</a> 


                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger mr-1" data-toggle="modal" data-target="#DeleteModal-@item.IdCliente">
                        <i class="fa fa-trash"></i>
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="DeleteModal-@item.IdCliente" tabindex="-1" role="dialog" aria-labelledby="DeleteModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="DeleteModalLabel">Excluir cliente</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Deseja realmente excluir o cliente @item.Nome ?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                                    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.IdCliente">Sim</a>
                                </div>
                            </div>
                        </div>
                    </div>


                </td>
            </tr>
        }
    </tbody>
</table>
@section Scripts {

    <script>
            let table = new DataTable('#myTable');

             

    </script>
}

teste/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

teste/Views/Livro/Create.cshtml
@model teste.DATA.Models.Livro

@{
    ViewData["Title"] = "Create";
}

<h1>Cadastrar livro</h1>

<h4>Preencha os campos abaixo para incluir um novo livro </h4>
<hr />
<div>
    <a class="btn btn-primary" asp-action="Index">Voltar</a>
</div>
<br />
<div class="row">
    <div class="col-md">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

           <div class="card-header">Informações do livro</div>
           <div class ="card-body">
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Editora" class="control-label"></label>
                <input asp-for="Editora" class="form-control" />
                <span asp-validation-for="Editora" class="text-danger"></span>
            </div>
           </div>
            <div class="form-group">
                <input type="submit" value="Inclur" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

teste/Views/Livro/Details.cshtml
@model teste.DATA.Models.Livro

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes do livro</h1>

<div>
    <h4>Livro</h4>
    <hr />
     <div>
       <a class="btn btn-success"asp-action="Edit" asp-route-id="@Model.IdLivro">Alterar</a> 
       <a class="btn btn-primary"asp-action="Index">Voltar</a>
     </div>
     <br />
      <div class="card"> 
                   <div class="card-header">Informações do livro</div>
                   <div class ="card-body">
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Editora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Editora)
        </dd>
    </dl>
</div>

teste/Views/Livro/Edit.cshtml
@model teste.DATA.Models.Livro

@{
    ViewData["Title"] = "Edit";
}

<h1>Alterar dados do cliente</h1>

<h4>Altere os dados abaixo</h4>
<hr />
<div>
    <a class="btn btn-primary"asp-action="Index">Voltar</a>
</div>
<br />
<div class="row">
    <div class="col-md">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdLivro" />
          <div class="card"> 
                   <div class="card-header">Informações do livro</div>
                   <div class ="card-body">
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Editora" class="control-label"></label>
                <input asp-for="Editora" class="form-control" />
                <span asp-validation-for="Editora" class="text-danger"></span>
           </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Incluir" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

teste/Views/Livro/Index.cshtml
@model IEnumerable<teste.DATA.Models.Livro>

@{
    ViewData["Title"] = "Index";
}
<h1>Livros</h1>
<p>
    <a class="btn btn-primary" asp-action="Create"> <i class="fa fa-plus-circle"></i> Novo Livro</a>
</p>
<table id="myTable" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Editora)
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
                <tr>
                    <td>
                    @Html.DisplayFor(modelItem => item.Titulo)
                    </td>
                    <td>
                    @Html.DisplayFor(modelItem => item.Autor)
                    </td>
                    <td>
                    @Html.DisplayFor(modelItem => item.Editora)
                    </td>
                  
                    <td class="row">
                        <a asp-action="Edit" class="btn btn-primary m-1" asp-route-id="@item.IdLivro"><i class="Alterar"></i></a>
                        <a asp-action="Details" class="btn btn-success m-1" asp-route-id="@item.IdLivro"><i class="Detalhes"></i></a>


                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-danger mr-1" data-toggle="modal" data-target="#DeleteModal-@item.IdLivro">
                            <i class="fa fa-trash"></i>
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="DeleteModal-@item.IdLivro" tabindex="-1" role="dialog" aria-labelledby="DeleteModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="DeleteModalLabel">Excluir livro</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Deseja realmente excluir o livro @item.Titulo ?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary " data-dismiss="modal">Não</button>
                                        <a asp-action="Delete" class="btn btn-danger " asp-route-id="@item.IdLivro">Sim</a>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </td>
                </tr>
        }
    </tbody>
</table>

@section Scripts {

<script>
        let table = new DataTable('#myTable');

</script>
}

teste/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Emprestimo de livros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
   
    <link rel="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/teste.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">teste</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VwEmprestimoController1" asp-action="Index">Emprestimo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Cliente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Livro" asp-action="Index">Livro</a>
                        </li>
                     
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Emprestimo de livro 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
   <script src="//code.jquery.com/jquery-3.5.1.js"></script>
    <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="~/js/all.min.js"></script>
    <script src="~/js/fontawesome.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

teste/Views/VwEmprestimoController1/Index.cshtml
@model IEnumerable<teste.DATA.Models.VwEmprestimo>


<h1>Emprestimo</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Cadastrar Emprestimo</a>
</p>
<table id="myTable" class="table">
    <thead>
        <tr>
            <th>
            @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.DataEmprestimo)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.DataDevolucao)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.DataEntregue)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
                <tr>
                    <td>
                @Html.DisplayFor(modelItem => item.Titulo)
                    </td>
                    <td>
                @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                @Html.DisplayFor(modelItem => item.DataEmprestimo)
                    </td>
                    <td>
                @Html.DisplayFor(modelItem => item.DataDevolucao)
                    </td>
                    <td>
                @Html.DisplayFor(modelItem => item.DataEntregue)
                    </td>
                    <td>
                    @{
                        var styleStatus = "text-white bg-success";

                        if (item.DataEntregue == true)
                        {
                            styleStatus = "";
                        }
                        else
                        {
                            if (DateTime.Now.Date > item.DataDevolucao.Date)
                            {
                                styleStatus = "text-white bg-danger";
                            }
                            else if (DateTime.Now.Date.Equals(item.DataDevolucao.Date))
                            {
                                styleStatus = "bg-warning";
                            }
                        }



                    }
                <td class="@styleStatus">

                        @Html.DisplayFor(modelItem => item.DataDevolucao)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.DataEntregue)
                </td>
                <td class="row">
                    <a asp-action="Edit" class="btn btn-primary mr-1" asp-route-id="@item.IdEmprestimo"><i class="fa fa-edit"></i></a>
                    <a asp-action="Details" class="btn btn-success mr-1" asp-route-id="@item.IdEmprestimo"><i class="fa fa-search"></i></a>


                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger mr-1" data-toggle="modal" data-target="#DeleteModal-@item.IdEmprestimo">
                        <i class="fa fa-trash"></i>
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="DeleteModal-@item.IdEmprestimo" tabindex="-1" role="dialog" aria-labelledby="DeleteModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="DeleteModalLabel">Excluir cliente</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Deseja realmente excluir o cliente @item.Nome ?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                                    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.IdEmprestimo">Sim</a>
                                </div>
                            </div>
                        </div>
                    </div>


                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts {
        <script>
            $(document).ready(function () {
                $('#myTable').DataTable({
                    "language": {
                        "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese-Brasil.json"
                    }
                });
            });
        </script>
}